version: "3.9"

services:
  app:
    build: .
    container_name: my_app
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_ECHO: ${DB_ECHO}
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: ["poetry", "run", "python3", "main.py"]

  db:
    image: postgres:15
    container_name: my_db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"

volumes:
  db_data:
